'use strict';
const mathMacros={"\\argmin":"\\operatorname*{arg\\,min}","\\argmax":"\\operatorname*{arg\\,max}","\\erfc":"\\operatorname{erfc}","\\sinc":"\\operatorname{sinc}","\\re":"\\operatorname{Re}","\\im":"\\operatorname{Im}","\\drm":"\\,\\mathrm{d}","\\EE":"\\mathrm{E}","\\PP":"\\mathbb{P}","\\RR":"\\mathbb{R}","\\CC":"\\mathbb{C}","\\x":"\\boldsymbol{x}","\\y":"\\boldsymbol{y}","\\X":"\\boldsymbol{X}","\\Y":"\\boldsymbol{Y}","\\Eb":"E_{\\mathrm b}","\\Es":"E_{\\mathrm s}","\\No":"N_0","\\snr":"\\mathrm{SNR}","\\px":"P_X","\\py":"P_Y","\\pyx":"P_{Y|X}","\\pxy":"P_{XY}","\\pxcy":"P_{X|Y}"};
const mathOptions={delimiters:[{left:'$$',right:'$$',display:true},{left:'\\[',right:'\\]',display:true},{left:'$',right:'$',display:false},{left:'\\(',right:'\\)',display:false}],macros:mathMacros,throwOnError:false,strict:false};
function math(el){el.querySelectorAll('.math:not([data-rendered])').forEach(node=>{katex.render(node.textContent,node,{...mathOptions,displayMode:node.classList.contains('display')});node.dataset.rendered='true'});renderMathInElement(el,mathOptions)}
math(document.body);
const expand=document.querySelector('#expand-solutions');if(expand)expand.addEventListener('click',()=>{const ds=[...document.querySelectorAll('details.solution')],open=!ds.every(d=>d.open);ds.forEach(d=>d.open=open);expand.textContent=open?'Hide all solutions':'Show all solutions'});
if(document.querySelector('#quiz')){
 fetch('quiz-bank.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(bank=>{
  let index=0,score=0,answered=false;const buttons=[...document.querySelectorAll('[data-answer]')],next=document.querySelector('#quiz-next'),feedback=document.querySelector('#quiz-feedback'),result=document.querySelector('#quiz-result'),card=document.querySelector('.quiz-card');
  function show(){answered=false;card.hidden=false;result.hidden=true;next.hidden=true;next.classList.remove('show');feedback.replaceChildren();feedback.className='quiz-feedback';document.querySelector('#quiz-progress').textContent=`Question ${index+1} of ${bank.length}`;const bar=document.querySelector('#quiz-bar');bar.style.width=(100*index/bank.length)+'%';document.querySelector('#quiz-concept').textContent=bank[index].concept;document.querySelector('#quiz-question').textContent=bank[index].statement;buttons.forEach(b=>{b.disabled=false;b.classList.remove('selected','correct','incorrect')});math(card)}
  buttons.forEach(b=>b.addEventListener('click',()=>{if(answered)return;answered=true;const correct=(b.dataset.answer==='true')===bank[index].answer;score+=Number(correct);b.classList.add(correct?'correct':'incorrect');feedback.className='quiz-feedback show '+(correct?'correct':'incorrect');buttons.forEach(x=>x.disabled=true);const verdict=document.createElement('strong');verdict.className=correct?'correct':'incorrect';verdict.textContent=correct?'Correct. ':'Incorrect. ';feedback.append(verdict,document.createTextNode(bank[index].explanation));math(feedback);next.textContent=index===bank.length-1?'See results':'Next question';next.hidden=false;next.classList.add('show');document.querySelector('#quiz-bar').style.width=(100*(index+1)/bank.length)+'%'}));
  next.addEventListener('click',()=>{if(!answered)return;index++;if(index<bank.length){show();buttons[0].focus()}else{card.hidden=true;result.hidden=false;result.innerHTML=`<h2>Practice complete</h2><p>You answered <strong>${score} of ${bank.length}</strong> questions correctly.</p><p><a href="exercises1.html">Continue with the exercises</a> or repeat the quiz.</p>`}});
  document.querySelector('#quiz-restart').addEventListener('click',()=>{index=0;score=0;show()});show();
 }).catch(()=>{document.querySelector('#quiz').textContent='The quiz could not load. Please reload this page.'});
}
